
== EUs politikk på området

EU-kommisjonens policy for tilgang til offentlige data omfatter all informasjon som offentlige organer produserer, samler inn eller betaler for. Eksempler er geografisk informasjon, statistikk, værdata, data fra offentlig finansierte forskningsprosjekter og digitaliserte bøker fra biblioteker. Policyen følger prinsippet om at offentlige data skal være mest mulig åpent tilgjengelige og gjenbrukbare.

EUs Åpne data direktiv - (https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32019L1024["ODD-direktivet"]) utgjør det lovmessige rammeverket for tilgang til offentlige data i EU og EØS. Direktivet bygger på to av grunnpilarene i EUs indre marked: transparens og rettferdig konkurranse. I tillegg ønsker EU-kommisjonen å sikre en mer effektiv utnyttelse av denne typen innhold over landegrensene. 

EUs Åpne data-direktiv definerer også (gjennom den tilhørende https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=pi_com%3AC%282022%299562[HVD-forordningen]) _datasett med høy verdi_ (High Value Datasets - HVD) innenfor seks tematiske kategorier: (1) geodata, (2) jordobservasjon og miljø, (3) meteorologi, (4) statistikk, (5) selskaper og eierskap, og (6) mobilitet.  HVD-forordningen stiller krav til at en rekke datasett i disse kategoriene skal gjøres tilgjengelige som åpne data, i maskinlesbare formater og via API-er. Det stilles også egne krav til beskrivelser (metadata) for HVD-ene, se Referansekatalogen for IT-standarder (https://www.digdir.no/1480[Referansekatalogen for IT-standarder]) for mer informasjon.

EU-kommisjonen finansierer en rekke åpne data-prosjekter, inkludert en europeisk dataportal, gjennom (https://www.digdir.no/internasjonalt-arbeid/digital-europa-programmet-digital-europe-programme/3192[DIGITAL Europa-programmet]). Midler for finansiering av digitaliseringsprosjekter under DIGITAL Europa-programmet lyses ut flere ganger i året. Både offentlige og private virksomheter kan søke om midler. Kontakt gjerne Digdir om du ønsker mer informasjon om finansieringsmuligheter i DIGITAL-programmet.