
== Gjeldende lovverk og IT-politikk for åpne offentlige data

Statens IT-politikk for tilgjengeliggjøring av offentlige data er beskrevet i https://www.regjeringen.no/no/dokumenter/meld.-st.-27-20152016/id2483795/[Digital agenda for Norge] og https://www.regjeringen.no/no/dokumenter/meld.-st.-22-20202021/id2841118/[Data ressurs - Datadrevet økonomi og innovasjon] som _gjenbruk_ og _viderebruk_, der _gjenbruk_ er offentlige virksomheters bruk av offentlige data, mens _viderebruk_ er privat sektors og sivilsamfunnets bruk av offentlige data.

Regjeringens mål om økt viderebruk er knyttet til målene om effektivisering og innovasjon, næringsutvikling og et åpent og demokratisk samfunn.

Regjeringens føringer for deling av åpne offentlige data er regulert i https://lovdata.no/dokument/NL/lov/2006-05-19-16?q=offentleglova[Lov om rett til innsyn i dokument i offentleg verksemd] (offentleglova),  https://www.regjeringen.no/id3103320/[Digitaliseringsrundskrivet] og regjeringens https://www.regjeringen.no/no/id2536870[Retningslinjer ved tilgjengeliggjøring av offentlige data]

NOTE: En ny lov for deling av data - "Datadelingsloven" er foreslått. Den er ment å erstatte viderebruksbestemmelsene for data i Offentleglova og implementere EUs Åpne data-direktiv i norsk lovgivning. Samtidig er det foreslått en ny lov om dataforvaltning for å gjennomføre EUs «dataforvaltningsforordning» (Data Governance Act – DGA). Offentleglova er gjeldende lov på området inntil nytt lovverk er vedtatt.

=== Offentleglova

https://lovdata.no/NL/lov/1814-05-17-nn/§100[Grunnlova § 100] slår fast at “alle har rett til innsyn i dokument til staten og kommunane. Retten til innsyn er presisert i offentleglova. Hovedregelen i offentleglova § 3 er at alle “saksdokument, journalar og liknande register for organet” er offentlig, det vil si omfattet av innsynsrett. Dokumentbegrepet i offentleglova er definert som “ei logisk avgrensa informasjonsmengd” og omfatter dermed også data som offentlig sektor forvalter. Offentleglova skal blant annet legge til rette for viderebruk av offentlig informasjon, og at offentlige sektor er åpen og gjennomsiktig (jf. https://lovdata.no/NL/lov/2006-05-19-16/§1[offentleglova § 1])

Informasjon som det er gitt tilgang til etter offentleglova kan brukes til ethvert formål, dersom ikke annen lovgivning eller retten til en tredjeperson er til hinder for det. Personopplysningsretten og opphavsretten er eksempler på rettigheter som begrenser muligheten for viderebruk.

Retten til innsyn er ikke ubegrenset. Mange dokumenter _skal_ eller _kan_ unntas fra offentlighet. Lovbestemt taushetsplikt unntar personlige forhold og forretningshemmeligheter fra innsynsretten. Dokumenter som kan lette gjennomføring av straffbare forhold, eller dokumenter som regnes som interne, kan unntas fra innsynsretten.

En oppdatering av Offentleglova i 2017 gir nå allmennheten rett til innsyn i alle eksisterende formater og språkversjoner av informasjonen det bes om innsyn i. Denne plikten gjelder også maskinlesbare formater.

Offentleglova gir altså allmennheten innsynsrett, det vil si at informasjon vil bli gjort tilgjengelig på forespørsel. Dette kan beskrives som en _reaktiv åpenhet_, og innsyn forutsetter at allmennheten har tilstrekkelig kunnskap til å stille relevante innsynskrav. Digitaliseringsrundskrivet legger opp til en mer _proaktiv åpenhet_, der egnet informasjon _skal_ gjøres tilgjengelig i maskinlesbare formater og synliggjøres på https://data.norge.no/[data.norge.no].

=== Digitaliseringsrundskrivet

Digitaliseringsrundskrivet gjelder for departementene, statens ordinære forvaltningsorganer, forvaltningsorganer med særskilte fullmakter og forvaltningsbedrifter.

Rundskrivet slår fast at den enkelte virksomhet skal ha tilstrekkelig oversikt over hvilke data den håndterer, hva de betyr og hva de kan brukes til. Dette innebærer at forvaltningen må ta stilling til hvilke data som kan gjøres tilgjengelig som åpne offentlige data.

Rundskrivet slår også fast at tilgjengeliggjøring av data skal skje i samsvar med regjeringens https://www.regjeringen.no/no/dokumenter/retningslinjer-ved-tilgjengeliggjoring-av-offentlige-data/id2536870/[Retningslinjer ved tilgjengeliggjøring av offentlige data] og viderebruksbestemmelsene i offentleglova.

=== Retningslinjer ved tilgjengeliggjøring av offentlige data

Regjeringens https://www.regjeringen.no/no/dokumenter/retningslinjer-ved-tilgjengeliggjoring-av-offentlige-data/id2536870/[Retningslinjer ved tilgjengeliggjøring av offentlige data] er en føring som består av 15 punkt og skal sikre best mulig utnyttelse av offentlige data. De mest grunnleggende punktene omhandler fraskrivelse av eventuell opphavsrett ved å bruke åpne standardlisenser, å tilby data gratis og å tilby data i maskinlesbare og standardiserte formater. Se kapitlet _Hvordan bør jeg tilby data?_ for mer informasjon om retningslinjene.
