name: build adocs and publish v1 to production

permissions:
  contents: read

on:
  push:
    branches:
      - v1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  upload-files-to-production:
    name: Upload guide to static-rdf-server
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v1
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D docs -o files/veileder-apne-data.pdf -a lang=nb docs/main.adoc
      host: https://fellesdatakatalog.digdir.no
      ontology: veileder-apne-data
      ontology-type: guide
      files: |
        docs/index.html text/html nb
        docs/files/veileder-apne-data.pdf application/pdf nb files/veileder-apne-data.pdf
        docs/images/Digdir.png image/png nb images/Digdir.png
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
